var bodyObj, index, classList;
index = -1;
bodyObj = document.getElementById("body");

classList = [
    'imageOne',
    'imageTwo',
    'imageThree',
    'imageFour',
    'imageFive',
    'imageSix',
    'imageSeven',
    'imageEight',
    'imageNine',
    'imageTen',
    'imageEleven',
    'imageTwelve',
    'imageThirteen',
    'imageFourteen',
    'imageFifteen',
    'imageSixteen',
    'imageSeventeen',
    'imageEighteen',
    'imageNineteen',
    'imageTwenty',
    'imageTwentyOne',
    'imageTwentyTwo',
    'imageTwentyThree',
    'imageTwentyFour',
    'imageTwentyFive',
    'imageTwentySix',
    'imageTwentySeven',
    'imageTwentyEight',
/*    'imageTwentyNine',
    'imageThirdty',
    'imageThirdtyOne',
    'imageThirdtyTwo',
    'imageThirdtyThree',
    'imageThirdtyFour',
    'imageThirdtyFive',
    'imageThirdtySix',
    'imageThirdtySeven',
    'imageThirdtyEight',
    'imageThirdtyNine',
    'imageFourty',
    'imageFourtyOne',
    'imageFourtyTwo',
    'imageFourtyThree',
    'imageFourtyFour',
    'imageFourtyFive',
    'imageFourtySix',
    'imageFourtySeven',
    'imageFourtyEight',
    'imageFourtyNine',
    'imageFifty',
    'imageFiftyOne',
    'imageFiftyTwo',
    'imageFiftyThree',
    'imageFiftyFour',
    'imageFiftyFive',
    'imageFiftySix',
    'imageFiftySeven',
    'imageFiftyEight',
    'imageFiftyNine',
    'imageSixty',
    'imageSixtyOne',
    'imageSixtyTwo',
    'imageSixtyThree',
    'imageSixtyFour',
    'imageSixtyFive',
    'imageSixtySix',
    'imageSixtySeven',
    'imageSixtyEight',
    'imageSixtyNine',
    'imageSeventy',
    'imageSeventyOne',
    'imageSeventyTwo',
    'imageSeventyThree',
    'imageSeventyFour',
    'imageSeventyFive',
    'imageSeventySix',
    'imageSeventySeven',
    'imageSeventyEight',
    'imageSeventyNine',
    'imageEighty',
    'imageEightyOne',
    'imageEightyTwo',
    'imageEightyThree',
    'imageEightyFour',
    'imageEightyFive',
    'imageEightySix',
    'imageEightySeven',
    'imageEightyEight',
    'imageEightyNine',
    'imageNinety',
    'imageNinetyOne',
    'imageNinetyTwo',
    'imageNinetyThree',
    'imageNinetyFour',
    'imageNinetyFive',
    'imageNinetySix',
    'imageNinetySeven',
    'imageNinetyEight',
    'imageNinetyNine',
    'imageOneHundred',
*/
]

function updateIndex() {
    if (index === (classList.length - 1)) {
        index = 0;
    } else {
        ++index;
    }
}

function changeElements() {
    updateIndex();
    bodyObj.className = classList[index];
}

changeElements();